### ISSUE TITLE
Why bind class methods 

### ISSUE THREAD

**Issue by yTakkar** [sivadass/react-shopping-cart#11]
We can use arrow functions to ignore binding

**Comment by yTakkar** [comment]
I know it can be a personal choice so you can ignore it :)

**Comment by sivadass** [comment]
Yeah of course, but when i wrote this project, I wasn't really much familiar with arrow functions :D

**Comment by yTakkar** [comment]
Can I transform the code into es6 and send a PR?

**Comment by sivadass** [comment]
Yeah sure ☺️
