### ISSUE TITLE
Unable to run shopping cart in localhost

### ISSUE THREAD

**Issue by khasimhk** [sivadass/react-shopping-cart#16]
I tried to run the shopping cart in mylocal its not working by following the steps which you have specified in readMe.txt.please help me to run  @sivadass

**Comment by sivadass** [comment]
In which step you are now?
What is the error message you are getting?

**Comment by khasimhk** [comment]
i am beginner for front end .........
after first step i.e npm install i tried with 2nd step which is webpack its
show command not found

**Comment by khasimhk** [comment]
Thanks a lot sivadass for your quick response. Last two days I was trying
to run the second step which is webpack.

May i know how to run webpack, I tried npm webpack which was not helpful. I
have installed webpack already.

If you can help me by providing command which i need to run from terminal
that would be very helpful.

Thanks Again
Khasim

**Comment by sivadass** [comment]
1. Just check your Webpack version first by `webpack -v`.
2. If your Webpack version is 4.X, then uninstall it by `npm uninstall -g webpack`
3.  Then install Webpack 3 globally by `npm install -g webpack@3.X`.

Now Webpack will for work.

**Comment by khasimhk** [comment]
Thank you for your valuable time!



I tried with your steps and its done installing webpack and  Webpack is
watching the files…as you said its throwing  cors error, for solution as
you mentioned i tried to set  const url="./products.json" in index.js  then
By copying the path by right clicking on index.hmtl  and pasted in browser
it is opening but not as expected i have attached the screenshot PFA.


Thanks & regards
khasim hk

**Comment by khasimhk** [comment]
Thank you! I really appreciate your timely help.

Its running in my local now. Let me have go through the code now in detail.

Regards
khasim hk

**Comment by sivadass** [comment]
Thanks for your feedback buddy :)
