### ISSUE TITLE
Blank page on IE 11

### ISSUE THREAD

**Issue by harshan89** [sivadass/react-shopping-cart#25]

**Comment by sivadass** [comment]
Added support for IE11 just clone updated repo and try...

![Screenshot 2019-05-16 at 12 13 54 AM](https://user-images.githubusercontent.com/10391786/57800767-ce6f8100-776f-11e9-95ff-1d0c8145c148.png)

Let me know if you got any errors?

**Comment by harshan89** [comment]
Thanks i'll check
