### ISSUE TITLE
CORS Failure

### ISSUE THREAD

**Issue by mahefnawy** [sivadass/react-shopping-cart#8]
I keep getting ```Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.``` error from the console even after I Changed the url to the local json file

**Comment by sivadass** [comment]
Are you sure, you are running the index.html on any http server and not via file system?

**Comment by mahefnawy** [comment]
I fixed it buy using webpack-dev-server, Thank you so much
