### ISSUE TITLE
post a license for this software

### ISSUE THREAD

**Issue by DoWhileGeek** [sivadass/react-shopping-cart#9]
No one that knows to care about software licenses will use your software in a commercial setting because there is no license posted. Can you decide on a license and add it to the codebase? If you're open to suggestion, an MIT license is ideal for commercial use purposes.

**Comment by sivadass** [comment]
I have added the [MIT License](https://github.com/sivadass/react-shopping-cart/blob/master/LICENSE) now. Use it without any worry :)

**Comment by DoWhileGeek** [comment]
Great, thanks!
